### ISSUE TITLE
train_list.txt

### ISSUE THREAD

**Issue by xiaoliangbai** [vinvino02/GLPDepth#10]
I notice that train_list.txt does not include all the images from NYU depth V2 dataset from bts. For example, images in study_room_0005b scene:
...
/study_room_0005b/rgb_00087.jpg /study_room_0005b/sync_depth_00087.png
/study_room_0005b/rgb_00089.jpg /study_room_0005b/sync_depth_00089.png
/study_room_0005b/rgb_00090.jpg /study_room_0005b/sync_depth_00090.png
/study_room_0005b/rgb_00092.jpg /study_room_0005b/sync_depth_00092.png
/study_room_0005b/rgb_00093.jpg /study_room_0005b/sync_depth_00093.png

Images such as rgb_00091.jpg, rgb_00094.jpg, etc. are missing from the list. 

It looks like images were selected to generate the final list used in the training process. What were the criteria used to select images for training?

Thanks

**Comment by vinvino02** [comment]
Hello, 
I just checked the nyudepthv2_train_files_with_gt.txt from bts repository [link](https://github.com/cleinc/bts/blob/master/train_test_inputs/nyudepthv2_train_files_with_gt.txt) and figured out there are no images 
/study_room_0005b/rgb_00093.jpg or /study_room_0005b/sync_depth_00091.jpg in their file as well as my train_list.txt. 
I think I have not selected some of the images from their files. Could you check this again?

**Comment by lighthappy** [comment]
你好，我是一个小白，可以提供一下这个train_list.txt的数据集下载地址吗？万分感谢
