### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by lighthappy** [vinvino02/GLPDepth#14]
Hello, I am a new student, I would like to ask you for the download link of the dataset about the file train_list. TXT data set, but I can't get it down.

**Comment by vinvino02** [comment]
Hello, 
Which dataset (kitti for nyu depth v2) are you referring to?

**Comment by lighthappy** [comment]
nyu depth v2
![image](https://user-images.githubusercontent.com/30305564/157454898-8fc6395c-0be5-4931-b420-23b256ee4ae9.png)

**Comment by vinvino02** [comment]
You should download [bts](https://github.com/cleinc/bts/tree/master/pytorch) repository and follow their instructions. 
In case of NYU Depth V2, you should run this command with their code. 
`
python utils/download_from_gdrive.py 1AysroWpfISmm-yRFGBgFTrLy6FjQwvwP ../dataset/nyu_depth_v2/sync.zip
`
