### ISSUE TITLE
How is the pretrained model mit_b4 obtained?

### ISSUE THREAD

**Issue by frspring** [vinvino02/GLPDepth#15]
Hi, I'm running your code and get a consistent result with your paper.
And I wonder how is the pretrained encoder model mit_b4 obtained? Is there any reference paper?

**Comment by vinvino02** [comment]
Hello, it is obtained from SegFormer: Simple and Efficient Design for Semantic Segmentation with Transformers. [[code]](https://github.com/NVlabs/SegFormer)
