### ISSUE TITLE
test on SUN-RGB

### ISSUE THREAD

**Issue by lighthappy** [vinvino02/GLPDepth#17]
Hello, I am a student and I would like to ask how to test on SUN RGB-D dataset and get the corresponding depth map? I hope the author can answer and give the code. Thanks, I hope to get your reply. Have a nice life.

**Comment by vinvino02** [comment]
Hi. You can get SUN RGB-D depth map from official sites (https://rgbd.cs.princeton.edu/). I'm sorry that I cannot provide the code for now, but it is quite simple to make the dataset code for SUN RGB-D depth map similar to uploaded NYU or KITTI dataset codes.
