### ISSUE TITLE
When will the training code be released?

### ISSUE THREAD

**Issue by ShuweiShao** [vinvino02/GLPDepth#2]
Hi! Thanks for the great work! When will the training code be released?

**Comment by vinvino02** [comment]
Thanks! It will be uploaded within 1-2 weeks.

**Comment by Paras-97** [comment]
Hi! Your work is really admirable! I was wondering when will the training code be uploaded? @vinvino02

**Comment by vinvino02** [comment]
Hello, I have uploaded the training codes. Thanks!
