### ISSUE TITLE
I can't download pre_trained mit_b4 .

### ISSUE THREAD

**Issue by hutingz** [vinvino02/GLPDepth#21]
print("Download pre-trained encoder weights...")
                id = '1BUtU42moYrOFbsMCE-LTTkUE-mrWnfG2'
                url = 'https://drive.google.com/uc?id=' + id
                output = './code/models/weights/mit_b4.pth'
                gdown.download(url, output, quiet=False)
I can't download mit_b4 。The probable reason is that this link has been downloaded by so many people that I can no longer download it。Can you provide a new download link? 
![image](https://user-images.githubusercontent.com/89053279/172050778-b2e73c5e-9432-474e-8e3e-70ec98d1ba11.png)

**Comment by vinvino02** [comment]
Try this download link https://drive.google.com/file/d/1BUtU42moYrOFbsMCE-LTTkUE-mrWnfG2/view?usp=sharing

**Comment by puyiwen** [comment]
> 试试这个下载链接https://drive.google.com/file/d/1BUtU42moYrOFbsMCE-LTTkUE-mrWnfG2/view?usp=sharing

hi,what is the mit_b4 pre-trained model input size?I find your network input size is 448x576,does this input size match the input size of the mit_b4 pre-trained model you provided?

**Comment by hutingz** [comment]
我不知道mit_b4预训练模型的输入大小是多少。我输入图片大小之所以是448*576，是因为GLPDepth这篇文章的NYU输入就是448*576.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月17日(星期三) 下午4:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vinvino02/GLPDepth] I can&#39;t download pre_trained mit_b4 . (Issue #21)





  
试试这个下载链接https://drive.google.com/file/d/1BUtU42moYrOFbsMCE-LTTkUE-mrWnfG2/view?usp=sharing
  
hi,what is the mit_b4 pre-trained model input size?I find your network input size is 448x576,does this input size match the input size of the mit_b4 pre-trained model you provided?

**Comment by umuthopeyildirim** [comment]
Hi @vinvino02 seems like link is dead. Can you give access to `umut475@gmail.com`?
<img width="801" alt="Screenshot 2024-01-03 at 2 58 08 PM" src="https://github.com/vinvino02/GLPDepth/assets/39514133/21a52638-251b-49aa-80ea-b59c1521fc97">
