### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [vinvino02/GLPDepth#3]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo

Thank you.

**Comment by vinvino02** [comment]
Thanks! Since this work is related to company project, we are still discussing about the license type. 
For now, I want to say this code is for non-commercial use only (research, evaluation etc).

**Comment by PINTO0309** [comment]
Thanks!

**Comment by vinvino02** [comment]
Thank you for your advice :) I will add caveat in the README shortly.
