### ISSUE TITLE
How to convert the depth prediction to absolute depth?

### ISSUE THREAD

**Issue by ASONG0506** [vinvino02/GLPDepth#35]
As the title described, the depth prediction max value is not equal to the gt depth which is much bigger, so how to get the scale factor to convert the prediction result to real depth value. thanks!

**Comment by Candy-Crusher** [comment]
Hi! Did you figure it out? I have the same issue right now...

**Comment by ASONG0506** [comment]
> Hi! Did you figure it out? I have the same issue right now...

No, I didn't solve it, I just set a pseudo scaling function as follow to do 3d visualize

`import cv2
import numpy as np
import json

from glpdepth import GLPDepth
from img3d import IMG3D
from pathlib import Path

import sys
FILE = Path(__file__).resolve()
ROOT = FILE.parents[2]  # depth parent dir
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))  # add ROOT to PATH
from utils import pcd_viewer


def pure_depth2pcd(img3d, pure_depth):
    '''
    convert relative depth data to abs depth info
    :param img3d:
    :param pure_depth:
    :return:
    '''
    shape = pure_depth.shape
    depth_points = []
    for i in range(150, shape[0]):
        for j in range(shape[1]):
            depth_points.append([j, i, 100*(1-pure_depth[i,j]/255.0)])

    pc_cam = img3d.depth2cam(depth_points)
    return pc_cam


if __name__ == "__main__":


    # Initialize model
    max_dist = 10.0
    model_path='models/glpdepth_kitti_736x1280/glpdepth_kitti_736x1280.onnx'
    depth_estimator = GLPDepth(model_path)

    # Read inference image
    # img = imread_from_url("https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/401_Gridlock.jpg/1280px-401_Gridlock.jpg")
    img = cv2.imread("./doc/img/1673243482653141362.jpg")

    # Estimate depth and colorize it
    depth_map = depth_estimator(img)
    color_depth, pure_depth_map = depth_estimator.draw_depth(max_dist)
    combined_img = np.hstack((img, color_depth))
    cv2.namedWindow("Estimated depth", cv2.WINDOW_NORMAL)
    cv2.imshow("Estimated depth", combined_img)
    cv2.waitKey(0)

    # get cam pcds and visualize
    pc_cam = pure_depth2pcd(img3d, pure_depth_map)
    pcd_viewer.visualize_np(pc_cam, [], True)

`

result as follow

![res](https://user-images.githubusercontent.com/26050577/221179312-b316d83f-a35b-43bd-9b76-1e7d38003c41.png)

![visualize_pcd](https://user-images.githubusercontent.com/26050577/221179348-410d7695-1673-446e-ba71-e0d5c7e54ec4.png)

**Comment by gliehu** [comment]
The labels of the NYUv2 dataset are absolute depth values. Why do we need to convert the estimated results? Can you explain this to me? Thank you.
