### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by Paras-97** [vinvino02/GLPDepth#4]
Hi, I was wondering when will you be uploading a google colab file? Thanks

**Comment by Paras-97** [comment]
Also, when I am trying to train the model, it is throwing this error.
FileNotFoundError: [Errno 2] No such file or directory: './code/models/weights'

Where can I download the weights from?

**Comment by vinvino02** [comment]
Hello, I'm planning to upload colab file within 1-2 weeks.

**Comment by vinvino02** [comment]
I modified model.py to automatically download weight file if it does not exist in the directory. Please check your model.py is same as the uploaded file.

**Comment by Paras-97** [comment]
Thanks.
