### ISSUE TITLE
How to convert depth map to point cloud

### ISSUE THREAD

**Issue by mcmingchang** [vinvino02/GLPDepth#5]
Great job，is there a similar conversion method? for example https://github.com/vitalemonate/depth2Cloud

**Comment by vinvino02** [comment]
Thanks. I don't know if it's the similar conversion method as you mentioned, but I have tried to visualize the depth map in 3D with the following code (https://github.com/CapObvios/Depth-Map-Visualizer).

**Comment by mcmingchang** [comment]
thank you
