### ISSUE TITLE
How to measure distance from depth map?

### ISSUE THREAD

**Issue by Paras-97** [vinvino02/GLPDepth#6]
Hi, Can you please tell how exactly to find distance from depth map?

**Comment by vinvino02** [comment]
The model trained on the NYU has a max range of 10m, and the model trained on the KITTI has 80m. Each pixel value of the generated depth map is in meters. If args.dataset is set as kitti, it is multiplied by 256, and in other cases, it is multiplied by 1000 and saved in to result directory.

**Comment by ronen756** [comment]
Hello @vinvino02, thank you very much for the answer. We are facing the same goal of measuring absolute distance from the prediction and I still have some questions: (I am using the code in the Google Collab)
1. I can't find any parameter called "args.dataset", can you please explain how do I know which pretrained model is used in the Google Collab and how can I change it there?
2. In the Google Collab sheet, there is this entity called "prediction" - is this what you call "depth map"? Does it output actual absolute distance from camera? Or is it relative distance, and I need to do some transformation to get the real distance?

I hope my questions are clear, thank you in advance!
