### ISSUE TITLE
a problem of metrics

### ISSUE THREAD

**Issue by WL678** [vinvino02/GLPDepth#8]
Hi，guys!
Firstly, thanks for the great paper and open source project!
I am trying to repeat your work. And I have downloaded  your model from the url in model.py. However,after testing,we found that the metrics had a significant difference from your results. So I wonder if it is convenient for you to provide me with a well-trained model.
Thanks a lot!

**Comment by vinvino02** [comment]
Thanks! 
The weight from the url in model.py is for the initialization of training model. 
You have to download trained model weights from https://drive.google.com/drive/folders/17yYbLZS2uQ6UVn5ET9RhVL0y_X3Ipl5_. Please check this.

**Comment by WL678** [comment]
Sorry， I found this web address is invalid.  are you sure this is the right url?

**Comment by vinvino02** [comment]
Could you check download link from Downloads section of README.md? 
![image](https://user-images.githubusercontent.com/73110522/155446229-d351087a-1d13-4141-9649-b371bc260c08.png)
